CREATE TABLE bloqueios_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profissional_id BIGINT NOT NULL REFERENCES profissionais(id),
    tipo VARCHAR(16) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    hora_inicio TIME(6),
    hora_fim TIME(6),
    motivo VARCHAR(180),
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_bloqueio_profissional_periodo
    ON bloqueios_agenda(profissional_id, data_inicio, data_fim);
