CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255), email VARCHAR(255), numero VARCHAR(255), senha VARCHAR(255) NOT NULL, role SMALLINT NOT NULL
);
CREATE TABLE vendedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, nome_loja VARCHAR(255) NOT NULL,
    hora_abertura TIME(6) NOT NULL, hora_fechamento TIME(6) NOT NULL, senha VARCHAR(255) NOT NULL, role SMALLINT NOT NULL
);
CREATE TABLE vendedor_dias_abertos (
    vendedor_id BIGINT NOT NULL REFERENCES vendedor(id), dia VARCHAR(9)
);
CREATE TABLE servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255), descricao VARCHAR(255), preco DOUBLE PRECISION, tempo TIME(6), vendedor_id BIGINT REFERENCES vendedor(id)
);
CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE, hora_inicio TIME(6), hora_fim TIME(6), status SMALLINT,
    cliente_id BIGINT REFERENCES clientes(id), vendedor_id BIGINT REFERENCES vendedor(id), servico_id BIGINT REFERENCES servicos(id)
);
