CREATE TABLE contas_profissionais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profissional_id BIGINT NOT NULL UNIQUE REFERENCES profissionais(id),
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(100),
    convite_token VARCHAR(64) UNIQUE,
    convite_expira_em TIMESTAMP(6),
    aceito_em TIMESTAMP(6),
    criado_em TIMESTAMP(6) NOT NULL
);
