CREATE TABLE assinaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estabelecimento_id BIGINT NOT NULL UNIQUE REFERENCES estabelecimentos(id),
    plano VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    teste_gratis_ate TIMESTAMP(6),
    mercado_pago_assinatura_id VARCHAR(120) UNIQUE,
    criado_em TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_assinaturas_estabelecimento ON assinaturas(estabelecimento_id);

-- Contas existentes permanecem no plano gratuito. O teste vale apenas para novas contas.
INSERT INTO assinaturas (estabelecimento_id, plano, status)
SELECT e.id, 'GRATUITO', 'ATIVA'
FROM estabelecimentos e
WHERE NOT EXISTS (
    SELECT 1 FROM assinaturas a WHERE a.estabelecimento_id = e.id
);

ALTER TABLE agendamentos
    ADD COLUMN criado_em TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_agendamentos_estabelecimento_criado_em
    ON agendamentos(estabelecimento_id, criado_em);
