CREATE TABLE profissionais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estabelecimento_id BIGINT NOT NULL REFERENCES estabelecimentos(id), nome VARCHAR(160) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE, criado_em TIMESTAMP(6) NOT NULL, atualizado_em TIMESTAMP(6) NOT NULL,
    legado_vendedor_id BIGINT
);
INSERT INTO profissionais (estabelecimento_id, nome, ativo, criado_em, atualizado_em, legado_vendedor_id)
SELECT estabelecimento_id, nome, TRUE, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), id FROM vendedor;
ALTER TABLE vendedor ADD COLUMN profissional_principal_id BIGINT;
UPDATE vendedor v SET profissional_principal_id = p.id FROM profissionais p WHERE p.legado_vendedor_id = v.id;
ALTER TABLE vendedor ADD CONSTRAINT uk_vendedor_profissional_principal UNIQUE (profissional_principal_id);
ALTER TABLE vendedor ADD CONSTRAINT fk_vendedor_profissional_principal FOREIGN KEY (profissional_principal_id) REFERENCES profissionais(id);
ALTER TABLE profissionais DROP COLUMN legado_vendedor_id;
CREATE INDEX idx_profissionais_estabelecimento_ativo ON profissionais (estabelecimento_id, ativo);
