import { ChangeEvent, CSSProperties, useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, Copy, ExternalLink, Image, Link2, QrCode, Scissors, UserRound, X } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { AdminShell } from '../components/AdminShell';
import { ApiError, bookingLink, catalogAppearance, myProfile, publicBusiness, saveCatalogAppearance, servicePhotoUrl, services } from '../services/api';
import type { BusinessProfile, CatalogAppearance, PublicBusiness, Service } from '../types';

interface Props { onExit: () => void; onSessionExpired: () => void; }
type EditorTab = 'Identidade' | 'Capa' | 'Conteúdo' | 'Layout';
const defaultAppearance = (name = 'Seu estabelecimento'): CatalogAppearance => ({ businessName: name, description: 'Atendimento feito com cuidado, no seu tempo.', primaryColor: '#E5674D', coverPositionX: 50, coverPositionY: 50, backgroundColor: '#F5F3EE', surfaceColor: '#FFFFFF', textColor: '#202B31', heroTextColor: '#FFFFFF', overlayOpacity: 80, fontStyle: 'moderna', cornerStyle: 'arredondado', heroAlignment: 'esquerda', heroSize: 'ampla', serviceLayout: 'grade', showServiceImages: true, showServiceDescriptions: true, showServiceDuration: true, heroEyebrow: 'AGENDAMENTO ONLINE', catalogTitle: 'O que você precisa hoje?' });
const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const appearanceFingerprint = (item: CatalogAppearance) => JSON.stringify({ businessName: item.businessName, description: item.description, primaryColor: item.primaryColor.toUpperCase(), logoImage: item.logoImage || null, coverImage: item.coverImage || null, coverPositionX: item.coverPositionX, coverPositionY: item.coverPositionY, backgroundColor: item.backgroundColor, surfaceColor: item.surfaceColor, textColor: item.textColor, heroTextColor: item.heroTextColor, overlayOpacity: item.overlayOpacity, fontStyle: item.fontStyle, cornerStyle: item.cornerStyle, heroAlignment: item.heroAlignment, heroSize: item.heroSize, serviceLayout: item.serviceLayout, showServiceImages: item.showServiceImages, showServiceDescriptions: item.showServiceDescriptions, showServiceDuration: item.showServiceDuration, heroEyebrow: item.heroEyebrow, catalogTitle: item.catalogTitle });

export function appearanceKey(code: string) { return `marquify-catalog-appearance:${code}`; }
export function loadAppearance(code: string, name?: string): CatalogAppearance {
  try { return { ...defaultAppearance(name), ...JSON.parse(localStorage.getItem(appearanceKey(code)) || '{}') }; }
  catch { return defaultAppearance(name); }
}
export function appearanceFromBusiness(business: PublicBusiness): CatalogAppearance {
  let theme = {}; try { theme = JSON.parse(business.temaPublico || '{}'); } catch { theme = {}; }
  return { ...defaultAppearance(business.nome), ...theme, businessName: business.nome, description: business.descricaoPublica || 'Atendimento feito com cuidado, no seu tempo.', primaryColor: business.corPrimaria || '#E5674D', logoImage: business.logoPublico || undefined, coverImage: business.capaPublica || undefined, coverPositionX: business.capaPosicaoX ?? 50, coverPositionY: business.capaPosicaoY ?? 50 };
}

export function PersonalizationPage({ onExit, onSessionExpired }: Props) {
  const [profile, setProfile] = useState<BusinessProfile | null>(null);
  const [catalog, setCatalog] = useState<Service[]>([]);
  const [publicLink, setPublicLink] = useState('');
  const [code, setCode] = useState('');
  const [appearance, setAppearance] = useState<CatalogAppearance>(() => defaultAppearance());
  const [tab, setTab] = useState<EditorTab>('Identidade');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState('');
  const [message, setMessage] = useState<{ kind: 'success' | 'error'; text: string } | null>(null);
  const [qrOpen, setQrOpen] = useState(false);
  const activeServices = useMemo(() => catalog.filter((item) => item.ativo).slice(0, 2), [catalog]);

  useEffect(() => {
    Promise.all([myProfile(), services(), bookingLink(), catalogAppearance()]).then(([me, items, link, savedAppearance]) => {
      setProfile(me); setCatalog(items); setPublicLink(link.urlAgendamento); setCode(link.codigoPublico);
      const loadedAppearance = appearanceFromBusiness(savedAppearance); setAppearance(loadedAppearance); setLastSaved(appearanceFingerprint(loadedAppearance));
    }).catch((error) => {
      if (error instanceof ApiError && error.status === 401) onSessionExpired();
      else setMessage({ kind: 'error', text: error instanceof ApiError ? error.message : 'Não foi possível carregar a personalização.' });
    }).finally(() => setLoading(false));
  }, [onSessionExpired]);

  const chooseImage = (field: 'coverImage' | 'logoImage') => (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { setMessage({ kind: 'error', text: 'Use uma imagem JPG, PNG ou WEBP de até 2 MB.' }); return; }
    const reader = new FileReader(); reader.onload = () => setAppearance((current) => ({ ...current, [field]: String(reader.result) })); reader.readAsDataURL(file);
  };
  const save = async (): Promise<boolean> => {
    if (!code || !appearance.businessName.trim()) return false;
    const updated = { ...appearance, businessName: appearance.businessName.trim(), description: appearance.description.trim() };
    setSaving(true);
    try { await saveCatalogAppearance(updated); const publicSaved = await publicBusiness(code); const confirmed = appearanceFromBusiness(publicSaved); if (appearanceFingerprint(confirmed) !== appearanceFingerprint(updated)) throw new Error('A API não devolveu a personalização enviada. Reinicie o backend e tente novamente.'); setAppearance(confirmed); setLastSaved(appearanceFingerprint(confirmed)); localStorage.removeItem(appearanceKey(code)); setMessage({ kind: 'success', text: 'Personalização publicada e confirmada na página pública.' }); return true; }
    catch (error) {
      if (error instanceof ApiError && error.status === 401) onSessionExpired();
      else setMessage({ kind: 'error', text: error instanceof Error ? error.message : 'Não foi possível salvar a personalização.' });
      return false;
    }
    finally { setSaving(false); }
  };
  const copy = () => { void navigator.clipboard?.writeText(publicLink); setMessage({ kind: 'success', text: 'Link público copiado.' }); };
  const openPublicPage = async () => { const target = window.open('', '_blank'); if (dirty && !(await save())) { target?.close(); return; } if (target) { target.opener = null; target.location.href = `${publicLink}?v=${Date.now()}`; } else window.location.href = `${publicLink}?v=${Date.now()}`; };

  const dirty = appearanceFingerprint(appearance) !== lastSaved;
  return <AdminShell title="Personalização" active="/personalizacao" userName={profile?.nome} onExit={onExit}><main className="dashboard-page personalization-page personalization-v2">
    <div className="page-heading personalization-heading"><div><p className="page-kicker">PÁGINA PÚBLICA</p><h1>Personalize sua página de agendamento.</h1><p>Ajuste a marca e veja ao lado o que o cliente verá no celular.</p></div><button className="primary-button" onClick={() => void save()} disabled={loading || saving || !dirty}>{saving ? 'Publicando…' : dirty ? 'Salvar e publicar' : 'Tudo publicado'}</button></div>
    {message && <div className={`admin-notice ${message.kind}`} role="status">{message.text}<button aria-label="Fechar mensagem" onClick={() => setMessage(null)}>×</button></div>}
    {loading ? <section className="dashboard-feedback"><p>Carregando editor…</p></section> : <div className="customization-layout personalization-workspace">
      <section className="panel editor-panel-dashboard public-editor"><div className="editor-heading"><div><h2>Editar página pública</h2><p>As alterações aparecem na prévia em tempo real.</p></div><span className={`live-badge ${dirty ? 'unsaved' : ''}`}><i /> {dirty ? 'Não publicado' : 'Publicado'}</span></div>
        <div className="editor-nav">{(['Identidade', 'Capa', 'Conteúdo', 'Layout'] as const).map((item) => <button type="button" className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div>
        {tab === 'Identidade' && <div className="editor-form"><label>Logotipo <small>aparece no topo da página</small><div className="logo-upload"><div className="logo-placeholder">{appearance.logoImage ? <img src={appearance.logoImage} alt="Logotipo" /> : <Scissors size={20} />}</div><div><strong>{appearance.logoImage ? 'Logotipo adicionado' : 'Use sua marca'}</strong><span>Imagem quadrada funciona melhor</span></div><label className="file-action">{appearance.logoImage ? 'Trocar' : 'Adicionar'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage('logoImage')} /></label>{appearance.logoImage && <button type="button" className="remove-image" onClick={() => setAppearance((current) => ({ ...current, logoImage: undefined }))}>Remover</button>}</div></label><label>Cor da marca<div className="color-picker"><input type="color" value={appearance.primaryColor} onChange={(event) => setAppearance((current) => ({ ...current, primaryColor: event.target.value.toUpperCase() }))} /><strong>{appearance.primaryColor}</strong><span>Usada em botões, seleção e destaques.</span></div></label></div>}
        {tab === 'Capa' && <div className="editor-form"><label>Imagem de capa <small>formato horizontal recomendado</small><label className="cover-upload-dashboard" style={appearance.coverImage ? { backgroundImage: `linear-gradient(#18283255,#18283255),url(${appearance.coverImage})`, backgroundPosition: `${appearance.coverPositionX}% ${appearance.coverPositionY}%` } : undefined}><div><Image size={25} /><span>{appearance.coverImage ? 'Trocar imagem' : <>Adicionar imagem de <b>capa</b></>}</span></div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage('coverImage')} /></label></label>{appearance.coverImage && <><div className="cover-position-controls"><strong>Enquadramento da capa</strong><p>Ajuste até a parte importante da foto aparecer na prévia.</p><label>Horizontal <span>{appearance.coverPositionX}%</span><input type="range" min="0" max="100" value={appearance.coverPositionX} onChange={(event) => setAppearance((current) => ({ ...current, coverPositionX: Number(event.target.value) }))} /></label><label>Vertical <span>{appearance.coverPositionY}%</span><input type="range" min="0" max="100" value={appearance.coverPositionY} onChange={(event) => setAppearance((current) => ({ ...current, coverPositionY: Number(event.target.value) }))} /></label></div><button type="button" className="secondary-danger" onClick={() => setAppearance((current) => ({ ...current, coverImage: undefined, coverPositionX: 50, coverPositionY: 50 }))}>Remover imagem de capa</button></>}</div>}
        {tab === 'Conteúdo' && <div className="editor-form"><label>Nome exibido<input className="catalog-text-input" value={appearance.businessName} maxLength={80} onChange={(event) => setAppearance((current) => ({ ...current, businessName: event.target.value }))} /></label><label>Texto acima do nome<input className="catalog-text-input" value={appearance.heroEyebrow} maxLength={40} onChange={(event) => setAppearance((current) => ({ ...current, heroEyebrow: event.target.value }))} /></label><label>Título da seção de serviços<input className="catalog-text-input" value={appearance.catalogTitle} maxLength={80} onChange={(event) => setAppearance((current) => ({ ...current, catalogTitle: event.target.value }))} /></label><label>Frase de apresentação<textarea value={appearance.description} maxLength={180} onChange={(event) => setAppearance((current) => ({ ...current, description: event.target.value }))} /><small className="field-counter">{appearance.description.length}/180</small></label><div className="editor-help-card"><strong>Os serviços vêm do seu catálogo</strong><p>Fotos, descrições, preços e duração são atualizados na aba Catálogo.</p></div></div>}
        {tab === 'Layout' && <div className="editor-form advanced-theme"><div className="theme-color-grid">{([['backgroundColor','Fundo'],['surfaceColor','Área do catálogo'],['textColor','Texto'],['heroTextColor','Texto da capa']] as const).map(([field,label]) => <label key={field}>{label}<div className="mini-color"><input type="color" value={appearance[field]} onChange={(event) => setAppearance((current) => ({ ...current, [field]: event.target.value.toUpperCase() }))} /><span>{appearance[field]}</span></div></label>)}</div><label>Escurecimento da foto <span>{appearance.overlayOpacity}%</span><input type="range" min="0" max="95" value={appearance.overlayOpacity} onChange={(event) => setAppearance((current) => ({ ...current, overlayOpacity: Number(event.target.value) }))} /></label><div className="theme-select-grid"><label>Tipografia<select value={appearance.fontStyle} onChange={(event) => setAppearance((current) => ({ ...current, fontStyle: event.target.value as CatalogAppearance['fontStyle'] }))}><option value="moderna">Moderna</option><option value="elegante">Elegante</option><option value="classica">Clássica</option></select></label><label>Cantos<select value={appearance.cornerStyle} onChange={(event) => setAppearance((current) => ({ ...current, cornerStyle: event.target.value as CatalogAppearance['cornerStyle'] }))}><option value="reto">Retos</option><option value="suave">Suaves</option><option value="arredondado">Arredondados</option></select></label><label>Alinhamento da capa<select value={appearance.heroAlignment} onChange={(event) => setAppearance((current) => ({ ...current, heroAlignment: event.target.value as CatalogAppearance['heroAlignment'] }))}><option value="esquerda">Esquerda</option><option value="centro">Centralizado</option></select></label><label>Tamanho da capa<select value={appearance.heroSize} onChange={(event) => setAppearance((current) => ({ ...current, heroSize: event.target.value as CatalogAppearance['heroSize'] }))}><option value="compacta">Compacta</option><option value="ampla">Ampla</option></select></label><label>Serviços<select value={appearance.serviceLayout} onChange={(event) => setAppearance((current) => ({ ...current, serviceLayout: event.target.value as CatalogAppearance['serviceLayout'] }))}><option value="grade">Grade</option><option value="lista">Lista</option></select></label></div><div className="visibility-options"><strong>O que aparece nos serviços</strong>{([['showServiceImages','Fotos'],['showServiceDescriptions','Descrições'],['showServiceDuration','Duração']] as const).map(([field,label]) => <label key={field}><input type="checkbox" checked={appearance[field]} onChange={(event) => setAppearance((current) => ({ ...current, [field]: event.target.checked }))} /> {label}</label>)}</div></div>}
        <div className={`publish-bar ${dirty ? 'has-changes' : ''} ${message?.kind === 'error' ? 'publish-error' : ''}`}><div><strong>{message?.kind === 'error' ? 'Não foi possível publicar' : dirty ? 'Você tem alterações não publicadas' : 'Página pública atualizada'}</strong><span>{message?.kind === 'error' ? message.text : dirty ? 'Publique para seus clientes receberem este visual.' : 'A versão da prévia está disponível no link.'}</span></div><button type="button" className="primary-button" disabled={saving || !dirty} onClick={() => void save()}>{saving ? 'Publicando…' : dirty ? 'Publicar alterações' : 'Publicado ✓'}</button></div>
        <div className="editor-footer"><span><Check size={14} /> {dirty ? 'Prévia local' : 'Sincronizado com a API'}</span><div><button type="button" onClick={() => setQrOpen(true)}><QrCode size={15} /> QR Code</button><button type="button" onClick={() => void openPublicPage()}>Abrir página <ExternalLink size={14} /></button></div></div>
      </section>
      <section className="catalog-preview-wrap public-preview-wrap"><div className="preview-label"><span>PRÉVIA DA PÁGINA PÚBLICA</span><span>Mobile</span></div><div className={`catalog-preview-phone public-page-preview preview-font-${appearance.fontStyle} preview-corners-${appearance.cornerStyle} preview-layout-${appearance.serviceLayout}`} style={{ '--preview-color': appearance.primaryColor, background: appearance.backgroundColor } as CSSProperties}>
        <div className={`public-preview-hero align-${appearance.heroAlignment} size-${appearance.heroSize}`} style={{ color: appearance.heroTextColor, ...(appearance.coverImage ? { backgroundImage: `linear-gradient(rgba(0,0,0,${appearance.overlayOpacity / 100}),rgba(0,0,0,${appearance.overlayOpacity / 100})),url(${appearance.coverImage})`, backgroundPosition: `${appearance.coverPositionX}% ${appearance.coverPositionY}%` } : { backgroundColor: appearance.primaryColor }) }}><div className="public-preview-logo">{appearance.logoImage ? <img src={appearance.logoImage} alt="" /> : <>marquify<span>.</span></>}</div><small>{appearance.heroEyebrow}</small><h2>Agende com<br /><i>{appearance.businessName || 'Seu estabelecimento'}</i></h2><p>{appearance.description || 'Escolha seu serviço e horário.'}</p></div>
        <div className="public-preview-body" style={{ background: appearance.surfaceColor, color: appearance.textColor }}><div className="public-preview-progress"><b>1 Serviço</b><span>2 Profissional</span><span>3 Horário</span></div><small>ESCOLHA SEU SERVIÇO</small><h3>{appearance.catalogTitle}</h3>{activeServices.map((service) => <div className="public-preview-service" key={service.id}>{appearance.showServiceImages && <div className="public-preview-photo">{service.fotoUrl ? <img src={servicePhotoUrl(service)} alt="" style={{ objectPosition: `${service.fotoPosicaoX}% ${service.fotoPosicaoY}%` }} /> : <Scissors size={15} />}</div>}<div><strong>{service.nome}</strong>{appearance.showServiceDescriptions && <span>{service.descricao || 'Conheça este atendimento.'}</span>}<small>{appearance.showServiceDuration && <>◷ {service.tempo.slice(0, 5)}</>} <b>{money(service.preco)}</b></small></div></div>)}{!activeServices.length && <p className="preview-empty">Adicione serviços ao catálogo para vê-los aqui.</p>}</div>
        <div className="public-preview-nav"><b><Scissors size={13} /> Catálogo</b><span><CalendarDays size={13} /> Agendamentos</span><span><UserRound size={13} /> Perfil</span></div></div>
        <div className="public-url"><Link2 size={15} /><span>{publicLink.replace(/^https?:\/\//, '')}</span><button type="button" onClick={copy} aria-label="Copiar link"><Copy size={14} /></button></div>
      </section>
    </div>}
    {qrOpen && <div className="qr-overlay" onClick={() => setQrOpen(false)}><div className="qr-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setQrOpen(false)} aria-label="Fechar"><X size={17} /></button><QRCodeSVG value={publicLink} size={150} level="M" includeMargin /><h2>Seu QR Code</h2><p>Clientes podem apontar a câmera para acessar sua página.</p></div></div>}
  </main></AdminShell>;
}
