import { FormEvent, useEffect, useState } from 'react';
import { CalendarDays, Check, Clock3, LogOut, Play } from 'lucide-react';
import { ApiError, acceptProfessionalInvite, login, logout, professionalAgenda, professionalProfile, updateProfessionalAppointment } from '../services/api';
import type { Appointment, Professional } from '../types';
import '../dashboard-v0-isolated.css';

const today = () => new Date().toISOString().slice(0, 10);
export function ProfessionalPortalPage() {
 const [profile,setProfile]=useState<Professional|null>(null); const [items,setItems]=useState<Appointment[]>([]); const [date,setDate]=useState(today()); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(Boolean(localStorage.getItem('marquify-token')));
 const load=()=>{setLoading(true);Promise.all([professionalProfile(),professionalAgenda(date)]).then(([p,a])=>{setProfile(p);setItems(a);}).catch(()=>{logout();setProfile(null);}).finally(()=>setLoading(false));};
 useEffect(()=>{if(localStorage.getItem('marquify-token')) load();},[date]);
 async function enter(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await login({login:String(f.get('email')),senha:String(f.get('senha'))});load();}catch(error){setMessage(error instanceof ApiError?'Não foi possível acessar esta área.':'E-mail ou senha inválidos.');}}
 async function status(id:number,next:'EM_ATENDIMENTO'|'CONCLUIDO'){try{const saved=await updateProfessionalAppointment(id,next);setItems(current=>current.map(item=>item.id===id?saved:item));}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível atualizar.');}}
 if(!profile&&!loading)return <main className="professional-portal"><section className="professional-login"><p className="page-kicker">ÁREA DO PROFISSIONAL</p><h1>Sua agenda, no seu ritmo.</h1><p>Entre para acompanhar seus atendimentos e atualizar o status do dia.</p><form onSubmit={enter}><label>E-mail<input name="email" type="email" required/></label><label>Senha<input name="senha" type="password" required/></label><button>Entrar na minha agenda</button>{message&&<small>{message}</small>}</form></section></main>;
 return <main className="professional-portal"><header><div><p className="page-kicker">MINHA AGENDA</p><h1>Olá, {profile?.nome?.split(' ')[0] || '…'}</h1></div><button onClick={() => { logout(); setProfile(null); }} aria-label="Sair"><LogOut size={18}/></button></header><section className="professional-day"><label><CalendarDays size={17}/> Data <input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><span>{items.filter(i => i.status !== 'CANCELADO').length} atendimentos</span></section>{loading ? <p>Carregando agenda…</p> : <section className="professional-list">{items.length ? items.map(item => <article key={item.id} className={item.status === 'CANCELADO' ? 'cancelled' : ''}><time>{item.horaInicio.slice(0,5)}<small>{item.horaFim.slice(0,5)}</small></time><div><strong>{item.cliente?.nome || 'Cliente'}</strong><span>{item.servico?.nome || 'Serviço'} · {item.status.replace('_',' ')}</span></div>{item.status === 'AGENDADO' && <button onClick={() => void status(item.id,'EM_ATENDIMENTO')}><Play size={14}/> Iniciar</button>}{item.status === 'EM_ATENDIMENTO' && <button onClick={() => void status(item.id,'CONCLUIDO')}><Check size={15}/> Concluir</button>}</article>) : <div className="dashboard-empty"><Clock3/><strong>Nenhum atendimento neste dia.</strong><span>Quando houver um agendamento, ele aparecerá aqui.</span></div>}</section>}</main>;
}
export function ProfessionalInvitePage({ token }: { token: string }) { const [message,setMessage]=useState(''); const [done,setDone]=useState(false); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const r=await acceptProfessionalInvite(token,String(new FormData(e.currentTarget).get('senha')));localStorage.setItem('marquify-token',r.token);setDone(true);}catch(error){setMessage(error instanceof Error?error.message:'Convite inválido.');}} return <main className="professional-portal"><section className="professional-login"><p className="page-kicker">CONVITE PARA A EQUIPE</p><h1>{done?'Acesso criado.':'Crie seu acesso.'}</h1><p>{done?'Você já pode abrir sua agenda individual.':'Defina uma senha para acessar sua agenda profissional.'}</p>{done?<a href="/profissional">Abrir minha agenda</a>:<form onSubmit={submit}><label>Nova senha<input name="senha" type="password" minLength={8} required/></label><button>Ativar meu acesso</button>{message&&<small>{message}</small>}</form>}</section></main>; }
